all:
	(cd src && $(MAKE) all)
	(cd c_src && $(MAKE) all)

release:
	(cd src && $(MAKE) release)
	(cd c_src && $(MAKE) release)

runtest:

clean:
	(cd src && $(MAKE) clean)
	(cd c_src && $(MAKE) clean)
